# Oh My Zsh location
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Modular configs
export ZSH_CONFIG_DIR="$HOME/.config/zsh"

for file in $ZSH_CONFIG_DIR/*.zsh; do
    source "$file"
done
